### ISSUE TITLE
V4 - Accès qui ne fonctionnent pas dans les ressources numériques

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/LaclasseService#1]
cf capture qui affiche les captures d'écrans montrant les message d'erreur.
Voici en résumé les ressources qui sont inaccessibles : 
- longman dictionary"
- CNS
- Sésamath
- le livre scolaire
- le site tv
- GPO
- BRNE Digithèque Bein
- BRNE Edulib

[tests 18-07-2017 ressources numeriques.pdf](https://github.com/laclasse-com/LaclasseService/files/1156280/tests.18-07-2017.ressources.numeriques.pdf)

**Comment by dlacroix** [comment]
correction et passage au SDET v6 pour Sesamath qui ne prend pas National_elv (SDET v4) mais uniquement National_ELV (SDET v5 et 6). Ne semble pas poser de problème pour les autres
