### ISSUE TITLE
V4 - Pouvoir créer un GPL avec un Ens

### ISSUE THREAD

**Issue by HuguesGithub** [laclasse-com/LaclasseService#2]
Lorsque je tente de créer un groupe libre avec un enseignant, j'ai une erreur 403.
Il faudrait donner les droits à un Enseignant de pouvoir créer des groupes libres.

curl 'https://v3dev.laclasse.com/api/groups' -X POST -H 'Accept: application/json, text/plain, */*' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.5' -H 'Content-Length: 135' -H 'Content-Type: application/json;charset=utf-8' -H 'Cookie: LACLASSE_AUTH=462DE9E006D4D408Hlxo54u44a' -H 'DNT: 1' -H 'Host: v3dev.laclasse.com' -H 'Origin: http://localhost:9292' -H 'Referer: http://localhost:9292/admin/' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0'

**Comment by dlacroix** [comment]
j'aurai aimé avoir le contenu de la requête POST

**Comment by dlacroix** [comment]
Je viens de rajouter ce droit aux enseignants pour les groupes libres.
