### ISSUE TITLE
V4 - problème dans l'affichage des tri admin panel d'une page à l'autre

### ISSUE THREAD

**Issue by CharlotteRizzo** [laclasse-com/LaclasseService#3]
Dans l'admin panel, lors d'un tri sur lastname le tri suivant ne se fait pas par ID. Avec plusieurs ID de même lastname, lorsqu'on change de page, le tri se fait de nouveau et les ID peuvent réapparaitre d'une page à l'autre.

**Comment by CharlotteRizzo** [comment]
Résolu dans la dev pour tous les comptes et sur tous les navigateurs

**Comment by dlacroix** [comment]
résolu aussi en prod
